name: A workflow for googlesearch
on: push

jobs:
    build:
      name: GoogleSearch action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
          with:
            MY_NAME: "Rakesh"